import { ChartPanel } from "@/components/chart-panel";
import { latestSummary, rangeConfig, timeSeries } from "@/lib/mnav-data";
import { formatCompactNumber, formatCurrency, formatDate, formatPercent } from "@/lib/format";

const latest = latestSummary();

export default function HomePage() {
  return (
    <main className="page-shell">
      <section className="hero">
        <div className="hero-copy">
          <p className="eyebrow">DAT.co mNAV Monitor</p>
          <h1>Strategy&apos;s equity premium versus its Bitcoin treasury, one day at a time.</h1>
          <p className="lede">
            This dashboard tracks modified net asset value (mNAV) for Strategy by combining daily BTC prices,
            MSTR market data, and a dated Bitcoin holdings timeline.
          </p>
        </div>
        <div className="hero-glow" aria-hidden="true" />
      </section>

      <section className="metrics-grid" aria-label="Latest indicator summary">
        <article>
          <span>Latest mNAV</span>
          <strong>{latest ? `${latest.mnav.toFixed(2)}x` : "N/A"}</strong>
          <p>{latest ? formatDate(latest.date) : "Dataset unavailable"}</p>
        </article>
        <article>
          <span>BTC Treasury NAV</span>
          <strong>{latest ? formatCurrency(latest.btcNav) : "N/A"}</strong>
          <p>{latest ? `${formatCompactNumber(latest.btcHoldings)} BTC held` : "Awaiting data"}</p>
        </article>
        <article>
          <span>Market Cap</span>
          <strong>{latest ? formatCurrency(latest.marketCap) : "N/A"}</strong>
          <p>{latest ? `${latest.ticker} close ${formatCurrency(latest.stockPrice)}` : "Awaiting data"}</p>
        </article>
        <article>
          <span>Premium to NAV</span>
          <strong>{latest ? formatPercent(latest.mnav - 1) : "N/A"}</strong>
          <p>Positive values imply the stock trades above treasury NAV.</p>
        </article>
      </section>

      <section className="workspace">
        <div className="workspace-head">
          <div>
            <p className="section-label">Daily Time Series</p>
            <h2>mNAV history</h2>
          </div>
          <p>
            Daily records: <strong>{timeSeries.length}</strong>
          </p>
        </div>
        <ChartPanel data={timeSeries} ranges={rangeConfig} />
      </section>

      <section className="two-column">
        <article>
          <p className="section-label">Methodology</p>
          <h2>How the indicator is computed</h2>
          <p>
            mNAV compares Strategy&apos;s market capitalization with the USD value of its Bitcoin holdings.
            The ratio is calculated as:
          </p>
          <pre>
            mNAV = marketCap / (btcHoldings * btcPrice)
          </pre>
          <p>
            Holdings change only on confirmed disclosure dates. Between disclosures, the latest confirmed
            holdings figure is carried forward to keep the daily series auditable and consistent.
          </p>
        </article>
        <article>
          <p className="section-label">BTC Linkage</p>
          <h2>Why it matters for Bitcoin analysis</h2>
          <p>
            BTC price moves change treasury NAV immediately. Strategy&apos;s stock can move faster or slower than
            that NAV, so mNAV shows whether the equity market is paying a premium for leverage, liquidity,
            management strategy, or Bitcoin optionality.
          </p>
          <ul>
            <li>Rising BTC with flat equity usually compresses mNAV.</li>
            <li>Rising equity faster than BTC expands mNAV.</li>
            <li>Large deviations often reflect sentiment, capital structure, or issuance expectations.</li>
          </ul>
        </article>
      </section>

      <section className="sources">
        <div>
          <p className="section-label">Sources</p>
          <h2>Dataset provenance</h2>
        </div>
        <ul>
          <li>BTC daily price: Binance daily BTCUSDT klines endpoint.</li>
          <li>MSTR daily price history: Nasdaq historical quote endpoint.</li>
          <li>Shares outstanding and holdings timeline: manually curated from Strategy disclosures.</li>
          <li>Processed dataset: generated by `scripts/build-dataset.mjs` into `data/processed/mstr-mnav.json`.</li>
        </ul>
      </section>
    </main>
  );
}
